import type { AppLocale } from "@/i18n/routing";

const english = {
  common: {
    mock: "Mock submission — your information is not persisted in this release.",
    required: "Required",
    next: "Continue",
    back: "Back",
    review: "Review",
    submit: "Submit to the mock adapter",
    confirmTitle: "Send this mock submission?",
    confirmBody:
      "The server will validate it and return a temporary response. No application or message is stored.",
    confirm: "Confirm mock submission",
    cancel: "Continue editing",
    loading: "Submitting…",
    successTitle: "The mock submission was accepted.",
    successBody:
      "This confirms the journey works; it does not mean Umoja received or stored your information.",
    duplicateTitle: "This looks like a duplicate mock submission.",
    duplicateBody:
      "The temporary server has already seen this email for this journey during its current process.",
    networkTitle: "The mock server could not be reached.",
    networkBody: "Your entries remain in this browser. Check the connection and try again.",
    validationTitle: "Some information needs attention.",
    retry: "Return to the form",
    reference: "Temporary reference",
    step: "Step {current} of {total}",
    progress: "Form progress",
    choose: "Choose an option",
    chooseMany: "Choose at least one",
    yes: "Yes",
    no: "No",
    errors: {
      required: "Enter this information before continuing.",
      email: "Enter an email address in the format name@example.com.",
      url: "Enter a complete link beginning with https://.",
      tooLong: "Shorten this response so it fits the allowed length.",
      chooseOne: "Choose at least one option before continuing.",
      consent: "Confirm this consent to submit the form.",
      needDetail: "Describe the need in at least 40 characters so the context is clear.",
      messageDetail: "Write at least 20 characters so we understand your message.",
      fileTooLarge: "Each selected file must be 10 MB or smaller.",
      tooManyFiles: "Select no more than three files.",
      date: "Enter a valid date.",
    },
  },
  project: {
    eyebrow: "Project intake",
    title: "Start with the need, not a sales script.",
    intro:
      "Share enough context for a responsible first review. This temporary journey does not store submissions.",
    steps: ["Contact", "Organization", "Project need", "Timing and files", "Review"],
    contactTitle: "How can the team follow up?",
    organizationTitle: "Tell us about the organization.",
    needTitle: "What needs to change or be built?",
    timingTitle: "What constraints should shape the first review?",
    reviewTitle: "Review the project context.",
    name: "Preferred contact name",
    email: "Private email",
    phone: "Phone number (optional)",
    organization: "Organization name",
    country: "Organization country or region",
    website: "Organization website (optional)",
    projectTitle: "Short project title",
    description: "Need, users, context, and constraints",
    descriptionHint: "Do not include secrets or regulated personal data.",
    services: "Relevant service areas",
    serviceOptions: [
      "Product engineering",
      "Data and AI",
      "Design and brand",
      "Cloud and enterprise",
      "Digital growth",
    ],
    budget: "Indicative budget band",
    budgetOptions: [
      "Still defining",
      "Under USD 10,000",
      "USD 10,000–50,000",
      "USD 50,000–150,000",
      "Above USD 150,000",
    ],
    desiredStart: "Desired timing",
    timingOptions: [
      "As soon as responsibly possible",
      "Within 1–3 months",
      "Within 3–6 months",
      "More than 6 months",
      "Still defining",
    ],
    targetDate: "Target date (optional)",
    files: "Supporting files (optional)",
    filesHint:
      "Up to three files, 10 MB each. Only filename, type, and size are sent to this mock; file contents are not uploaded.",
    consent:
      "I consent to Umoja using this project information to assess and respond to this request.",
  },
  talent: {
    eyebrow: "Talent application",
    title: "Bring your practice, evidence, and availability.",
    intro:
      "This private application journey is separate from optional public-profile visibility and does not store submissions yet.",
    steps: ["Profile", "Practice", "Portfolio", "Availability", "Consent", "Review"],
    profileTitle: "Your private application profile.",
    practiceTitle: "Where do you contribute strongest?",
    portfolioTitle: "Add portfolio context without restricted material.",
    availabilityTitle: "Describe your current availability.",
    consentTitle: "Choose each consent separately.",
    reviewTitle: "Review the private application.",
    name: "Preferred or public professional name",
    email: "Private email",
    phone: "Private phone number (optional)",
    country: "Country or region",
    timezone: "Timezone",
    skills: "Skill areas",
    skillOptions: [
      "Product management",
      "Software engineering",
      "Data and AI",
      "Design and research",
      "Cloud and operations",
      "Digital growth",
    ],
    experience: "Experience band",
    experienceOptions: [
      "Emerging practice",
      "Independent contributor",
      "Senior contributor",
      "Lead or principal",
    ],
    portfolioTitleLabel: "Portfolio item title",
    portfolioUrl: "Portfolio link (optional)",
    portfolioHint:
      "Do not include client-confidential work. Legal identity documents are not requested at this stage.",
    weekly: "Weekly capacity",
    weeklyOptions: [
      "Under 5 hours",
      "5–10 hours",
      "11–20 hours",
      "21–30 hours",
      "More than 30 hours",
    ],
    availableDate: "Next available date (optional)",
    workMode: "Preferred work mode",
    workModeOptions: ["Remote", "Hybrid where practical", "On-site where practical", "Flexible"],
    languages: "Working languages",
    languageOptions: [
      "English",
      "French",
      "Arabic",
      "Portuguese",
      "Swahili",
      "Other African language",
    ],
    publicConsent:
      "I optionally consent to a limited public profile after review. Leaving this unchecked does not affect my application.",
    applicationConsent:
      "I consent to submit this private application for Umoja’s contributor review.",
    dataConsent: "I consent to the processing of the application information described here.",
  },
  contact: {
    eyebrow: "Contact Umoja",
    title: "A direct route for questions and context.",
    intro:
      "Use this short journey when project or talent intake is not the right fit. Messages are not stored in this mock release.",
    steps: ["Message", "Review"],
    messageTitle: "What would you like to discuss?",
    reviewTitle: "Review your message.",
    name: "Preferred name",
    email: "Email",
    organization: "Organization (optional)",
    subject: "Subject",
    message: "Message",
    consent: "I consent to Umoja using these details to respond to this message.",
  },
} as const;

type DeepWiden<T> = T extends string
  ? string
  : T extends readonly (infer Item)[]
    ? readonly DeepWiden<Item>[]
    : T extends object
      ? { readonly [Key in keyof T]: DeepWiden<T[Key]> }
      : T;

export type IntakeCopy = DeepWiden<typeof english>;

const french: IntakeCopy = {
  common: {
    mock: "Envoi simulé — vos informations ne sont pas conservées dans cette version.",
    required: "Obligatoire",
    next: "Continuer",
    back: "Retour",
    review: "Vérifier",
    submit: "Envoyer à l’adaptateur simulé",
    confirmTitle: "Envoyer cette demande simulée ?",
    confirmBody:
      "Le serveur la validera et renverra une réponse temporaire. Aucune candidature ni aucun message ne sera conservé.",
    confirm: "Confirmer l’envoi simulé",
    cancel: "Continuer la modification",
    loading: "Envoi en cours…",
    successTitle: "La demande simulée a été acceptée.",
    successBody:
      "Cela confirme le fonctionnement du parcours ; Umoja n’a ni reçu ni conservé vos informations.",
    duplicateTitle: "Cette demande simulée semble être un doublon.",
    duplicateBody:
      "Le serveur temporaire a déjà vu cet e-mail pour ce parcours pendant son processus actuel.",
    networkTitle: "Le serveur simulé est inaccessible.",
    networkBody: "Vos saisies restent dans ce navigateur. Vérifiez la connexion puis réessayez.",
    validationTitle: "Certaines informations doivent être corrigées.",
    retry: "Retourner au formulaire",
    reference: "Référence temporaire",
    step: "Étape {current} sur {total}",
    progress: "Progression du formulaire",
    choose: "Choisir une option",
    chooseMany: "Choisissez au moins une option",
    yes: "Oui",
    no: "Non",
    errors: {
      required: "Renseignez cette information avant de continuer.",
      email: "Saisissez une adresse e-mail au format nom@exemple.com.",
      url: "Saisissez un lien complet commençant par https://.",
      tooLong: "Raccourcissez cette réponse pour respecter la longueur autorisée.",
      chooseOne: "Choisissez au moins une option avant de continuer.",
      consent: "Confirmez ce consentement pour envoyer le formulaire.",
      needDetail:
        "Décrivez le besoin en au moins 40 caractères afin que le contexte soit suffisamment clair pour une première analyse responsable.",
      messageDetail:
        "Rédigez au moins 20 caractères afin que nous comprenions précisément votre message.",
      fileTooLarge: "Chaque fichier sélectionné doit peser au maximum 10 Mo.",
      tooManyFiles: "Sélectionnez au maximum trois fichiers.",
      date: "Saisissez une date valide.",
    },
  },
  project: {
    eyebrow: "Dépôt de projet",
    title: "Commencer par le besoin, pas par un argumentaire commercial.",
    intro:
      "Partagez assez de contexte pour une première analyse responsable. Ce parcours temporaire ne conserve aucune demande.",
    steps: ["Contact", "Organisation", "Besoin", "Calendrier et fichiers", "Vérification"],
    contactTitle: "Comment l’équipe peut-elle vous répondre ?",
    organizationTitle: "Présentez-nous l’organisation.",
    needTitle: "Que faut-il transformer ou construire ?",
    timingTitle: "Quelles contraintes doivent guider la première analyse ?",
    reviewTitle: "Vérifiez le contexte du projet.",
    name: "Nom de contact préféré",
    email: "E-mail privé",
    phone: "Numéro de téléphone (facultatif)",
    organization: "Nom de l’organisation",
    country: "Pays ou région de l’organisation",
    website: "Site de l’organisation (facultatif)",
    projectTitle: "Titre court du projet",
    description: "Besoin, utilisateurs, contexte et contraintes",
    descriptionHint: "N’incluez aucun secret ni aucune donnée personnelle réglementée.",
    services: "Domaines de service pertinents",
    serviceOptions: [
      "Ingénierie produit",
      "Données et IA",
      "Design et marque",
      "Cloud et organisations",
      "Croissance numérique",
    ],
    budget: "Fourchette budgétaire indicative",
    budgetOptions: [
      "En cours de définition",
      "Moins de 10 000 USD",
      "10 000–50 000 USD",
      "50 000–150 000 USD",
      "Plus de 150 000 USD",
    ],
    desiredStart: "Calendrier souhaité",
    timingOptions: [
      "Dès que possible de manière responsable",
      "Sous 1 à 3 mois",
      "Sous 3 à 6 mois",
      "Dans plus de 6 mois",
      "En cours de définition",
    ],
    targetDate: "Date cible (facultative)",
    files: "Fichiers d’appui (facultatifs)",
    filesHint:
      "Jusqu’à trois fichiers de 10 Mo. Seuls le nom, le type et la taille sont envoyés à cette simulation ; leur contenu n’est pas téléversé.",
    consent:
      "J’accepte qu’Umoja utilise ces informations pour analyser ce projet et répondre à cette demande.",
  },
  talent: {
    eyebrow: "Candidature talent",
    title: "Apportez votre pratique, vos preuves et vos disponibilités.",
    intro:
      "Ce parcours privé est distinct de la visibilité publique facultative et ne conserve pas encore les candidatures.",
    steps: ["Profil", "Pratique", "Portfolio", "Disponibilité", "Consentements", "Vérification"],
    profileTitle: "Votre profil privé de candidature.",
    practiceTitle: "Dans quels domaines contribuez-vous le mieux ?",
    portfolioTitle: "Ajoutez du contexte sans contenu confidentiel.",
    availabilityTitle: "Décrivez votre disponibilité actuelle.",
    consentTitle: "Choisissez chaque consentement séparément.",
    reviewTitle: "Vérifiez la candidature privée.",
    name: "Nom professionnel préféré ou public",
    email: "E-mail privé",
    phone: "Téléphone privé (facultatif)",
    country: "Pays ou région",
    timezone: "Fuseau horaire",
    skills: "Domaines de compétence",
    skillOptions: [
      "Gestion de produit",
      "Ingénierie logicielle",
      "Données et IA",
      "Design et recherche",
      "Cloud et opérations",
      "Croissance numérique",
    ],
    experience: "Niveau d’expérience",
    experienceOptions: [
      "Pratique émergente",
      "Contributeur autonome",
      "Contributeur senior",
      "Responsable ou principal",
    ],
    portfolioTitleLabel: "Titre de l’élément de portfolio",
    portfolioUrl: "Lien du portfolio (facultatif)",
    portfolioHint:
      "N’incluez aucun travail confidentiel. Aucun document d’identité légale n’est demandé à ce stade.",
    weekly: "Capacité hebdomadaire",
    weeklyOptions: [
      "Moins de 5 heures",
      "5–10 heures",
      "11–20 heures",
      "21–30 heures",
      "Plus de 30 heures",
    ],
    availableDate: "Prochaine date disponible (facultative)",
    workMode: "Mode de travail préféré",
    workModeOptions: [
      "À distance",
      "Hybride lorsque possible",
      "Sur site lorsque possible",
      "Flexible",
    ],
    languages: "Langues de travail",
    languageOptions: [
      "Anglais",
      "Français",
      "Arabe",
      "Portugais",
      "Swahili",
      "Autre langue africaine",
    ],
    publicConsent:
      "J’accepte facultativement un profil public limité après validation. Ne pas cocher cette case n’affecte pas ma candidature.",
    applicationConsent:
      "J’accepte d’envoyer cette candidature privée pour l’examen des contributeurs Umoja.",
    dataConsent: "J’accepte le traitement des informations de candidature décrites ici.",
  },
  contact: {
    eyebrow: "Contacter Umoja",
    title: "Une voie directe pour vos questions et votre contexte.",
    intro:
      "Utilisez ce court parcours lorsque le dépôt de projet ou la candidature ne conviennent pas. Les messages ne sont pas conservés dans cette version simulée.",
    steps: ["Message", "Vérification"],
    messageTitle: "De quoi souhaitez-vous discuter ?",
    reviewTitle: "Vérifiez votre message.",
    name: "Nom préféré",
    email: "E-mail",
    organization: "Organisation (facultative)",
    subject: "Objet",
    message: "Message",
    consent: "J’accepte qu’Umoja utilise ces informations pour répondre à ce message.",
  },
};

export function getIntakeCopy(locale: AppLocale): IntakeCopy {
  return locale === "fr" ? french : english;
}
