import "server-only";

import { parseAppwriteEnvironment } from "@umoja/appwrite/env";

export function getServerAppwriteEnvironment() {
  return parseAppwriteEnvironment({
    NEXT_PUBLIC_APPWRITE_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT,
    NEXT_PUBLIC_APPWRITE_PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
    APPWRITE_SSR_API_KEY: process.env.APPWRITE_SSR_API_KEY,
    APPWRITE_SERVER_API_KEY: process.env.APPWRITE_SERVER_API_KEY,
    APPWRITE_BOOTSTRAP_API_KEY: process.env.APPWRITE_BOOTSTRAP_API_KEY,
    APPWRITE_DATA_ENCRYPTION_KEY_V1: process.env.APPWRITE_DATA_ENCRYPTION_KEY_V1,
    APPWRITE_FILE_ENCRYPTION_KEY_V1: process.env.APPWRITE_FILE_ENCRYPTION_KEY_V1,
    APPWRITE_LOOKUP_HMAC_KEY_V1: process.env.APPWRITE_LOOKUP_HMAC_KEY_V1,
    APPWRITE_ACTIVE_ENCRYPTION_KEY_VERSION: process.env.APPWRITE_ACTIVE_ENCRYPTION_KEY_VERSION,
    APPWRITE_DATABASE_ID: process.env.APPWRITE_DATABASE_ID,
    APPWRITE_CMS_PAGES_TABLE_ID: process.env.APPWRITE_CMS_PAGES_TABLE_ID,
    APPWRITE_CMS_REVISIONS_TABLE_ID: process.env.APPWRITE_CMS_REVISIONS_TABLE_ID,
    APPWRITE_PROJECT_INTAKES_TABLE_ID: process.env.APPWRITE_PROJECT_INTAKES_TABLE_ID,
    APPWRITE_TALENT_INTAKES_TABLE_ID: process.env.APPWRITE_TALENT_INTAKES_TABLE_ID,
    APPWRITE_AUDIT_LOGS_TABLE_ID: process.env.APPWRITE_AUDIT_LOGS_TABLE_ID,
    APPWRITE_CMS_MEDIA_BUCKET_ID: process.env.APPWRITE_CMS_MEDIA_BUCKET_ID,
    APPWRITE_INTAKE_FILES_BUCKET_ID: process.env.APPWRITE_INTAKE_FILES_BUCKET_ID,
    APP_URL: process.env.APP_URL,
    NEXT_REVALIDATION_SECRET: process.env.NEXT_REVALIDATION_SECRET,
  });
}
